### PR TITLE
added Indonesian language

### PR DESCRIPTION
**Pull request by theonlyonerzk**

### CODE REVIEW

**Comment by mqudsi** [comment]
Thank you! Is this ready to be merged or are you working on more improvements?

**Comment by theonlyonerzk** [comment]
yes, it's ready

**Comment by mqudsi** [comment]
I've merged this into the repository and it'll be included in the upcoming EasyBCD release. 

Please let me know how you would like your name to be mentioned in the list of translators (example list: https://github.com/neosmart/EasyBCD-Localization).

**Comment by theonlyonerzk** [comment]
Thank you for letting me know that my pull request has been merged into the repository and will be included in the upcoming EasyBCD release. I'm glad to have been able to contribute to the project.

As for my name, please include it in the list of translators as "Indonesian (Bahasa Indonesia) - rz.k". Thank you for your time and consideration.

**Comment by mqudsi** [comment]
No problem! I've updated the README in 26b47c862e7b5215aeab0b13ce4037fd3a432ba3.

**Pull request merged**
